[package]
name = "0azuree/doge-remote-build"
version = "0.2.1"
description = "Doge project built remotely via custom npm/Vite script."

[dependencies]
"wasmer/static-web-server" = "^1"

# The final, built assets will be in the 'dist' directory, 
# which we map to the web server's root ('/public').
[fs]
"/public" = "dist"

[[command]]
name = "start"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

# CRITICAL: Define the custom build process here.
# This runs 'npm install' then 'npm run build' remotely.
[build]
program = "sh"
program_args = ["-c", "npm install && npm run build"]
program_dir = "."
